from enum import Enum


class CmdTypes(Enum):
    GATHER_PROJECT_UNITS_OF_WORK = "GATHER_PROJECT_UNITS_OF_WORK"
    BUILD_UNIT_OF_WORK_TREE = "BUILD_UNIT_OF_WORK_TREE"
    CLONE_UNIT_OF_WORK = "CLONE_UNIT_OF_WORK"
    BULK_CREATE_UNITS_OF_WORK = "BULK_CREATE_UNITS_OF_WORK"
    CREATE_DASHBOARD = "CREATE_DASHBOARD"
    PERSIST_TO_STORE = "PERSIST_TO_STORE"
    BULK_PERSIST_TO_STORE = "BULK_PERSIST_TO_STORE"
    UPDATE_UNIT_OF_WORK = "UPDATE_UNIT_OF_WORK"
    UPDATE_UNIT_OF_WORK_HIERARCHY = "UPDATE_UNIT_OF_WORK_HIERARCHY"
    BUILD_WORKFLOW = "BUILD_WORKFLOW"
