
export const Configs = {
  DAPR_PROJS_STATE_STORE_NAME: "statestore-projs",
  DAPR_AZDO_STATE_STORE_NAME: "statestore-azdo",
  DAPR_USRS_STATE_STORE_NAME: "statestore-usrs",
  DAPR_PROCS_STATE_STORE_NAME: "statestore-procs",
  DAPR_STRUCTS_STATE_STORE_NAME: "statestore-structs",
  DAPR_PUBSUB_NAME: "pubsub",
  DAPR_CMD_WORKFLOW_PUBSUB_NAME: "pubsub-cmd-workflow",
  DAPR_CMD_RECEIPT_PUBSUB_NAME: "pubsub-cmd-receipt",
  GATHER_TOPIC: "MNDY_CMD_GATHER",
  STRUCTURE_TOPIC: "MNDY_CMD_STRUCTURE",
  AZDO_PROXY_TOPIC: "MNDY_CMD_AZDO_PROXY",
  WORKFLOW_TOPIC: "MNDY_CMD_WORKFLOW",
  GATHER_RECEIPT_TOPIC: "MNDY_CMD_GATHER_RECEIPT",
  STRUCTURE_RECEIPT_TOPIC: "MNDY_CMD_STRUCTURE_RECEIPT",
  AZDO_PROXY_RECEIPT_TOPIC: "MNDY_CMD_AZDO_PROXY_RECEIPT",
}

export enum CmdTypes {
  GATHER_PROJECT_UNITS_OF_WORK = "GATHER_PROJECT_UNITS_OF_WORK",
  BUILD_UNIT_OF_WORK_TREE = "BUILD_UNIT_OF_WORK_TREE",
  CLONE_UNIT_OF_WORK = "CLONE_UNIT_OF_WORK",
  BULK_CREATE_UNITS_OF_WORK = "BULK_CREATE_UNITS_OF_WORK",
  CREATE_DASHBOARD = "CREATE_DASHBOARD",
  PERSIST_TO_STORE = "PERSIST_TO_STORE",
  UPDATE_UNIT_OF_WORK = "UPDATE_UNIT_OF_WORK",
  UPDATE_UNIT_OF_WORK_HIERARCHY = "UPDATE_UNIT_OF_WORK_HIERARCHY",
  BUILD_WORKFLOW = "BUILD_WORKFLOW",
}

export const PartitionKeys = {
  PROJS: "projs",
}