apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-brand-insights
scopes:
  - mndy-dapr-mcp
  - mndy-dapr-actor-svc
  - mndy-cc-svc
spec:
  type: state.mongodb
  version: v1
  initTimeout: 5m
  metadata:
  - name: host
    value: "mongo-mndy:27017"
  - name: databaseName
    value: "mndy"
  - name: collectionName
    value: "brand-insights"
  - name: keyPrefix
    value: "none"
  - name: params
    value: "?authSource=admin&replicaSet=rs0&directConnection=true"
  - name: actorStateStore
    value: "true"
